In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
path = r'C:\Users\zzsgdsg7\Desktop\dis.xlsx'
data=pd.read_excel(path)
data.head()

Unnamed: 0      1431A    1432A\n    1433A\n    1434A\n    1435A\n  \
0      1431A   0.000000  29.645382  27.469353  23.253223  16.773911   
1    1432A\n  29.645382   0.000000  16.242188  10.715650  13.281899   
2    1433A\n  27.469353  16.242188   0.000000   7.896498  14.085749   
3    1434A\n  23.253223  10.715650   7.896498   0.000000   7.700973   
4    1435A\n  16.773911  13.281899  14.085749   7.700973   0.000000   

     1436A\n    1437A\n     1438A\n     1878A\n  ...      2573A\n  \
0  22.029474  20.077873  577.024294  128.843778  ...  1083.064269   
1  14.953309  13.120824  600.620794  111.793217  ...  1105.867030   
2  10.667940  10.196246  597.844002  127.816225  ...  1097.914459   
3   9.500538   6.386472  594.572575  122.089458  ...  1097.384295   
4   9.040237   5.369831  590.885126  120.557970  ...  1095.665012   

       2574A\n      2575A\n     2835A\n    2880A\n     2914A\n     2915A\n  \
0  1081.507009  1056.282105  904.103135  18.328024  351.065700  294.814080   
1  1104.285993  1079.114499  925.241169  16.120677  351.307084  278.426417   
2  1096.315185  1071.014916  913.975431  11.317199  361.163563  292.915866   
3  1095.796862  1070.563082  915.505018   8.880234  354.544361  287.022824   
4  1094.090773  1068.872998  915.121834   6.493452  352.931401  287.354524   

      3027A\n     3028A\n    3136A\n  
0  246.252755  235.835951  36.459368  
1  222.742099  212.282561  38.915788  
2  218.886001  208.398767  37.009491  
3  224.387189  213.810327  33.793193  
4  231.436210  221.015125  35.137369  

[5 rows x 101 columns]

In [19]:
#实现等距分隔一列数据
#a = data.iloc[:,3]

#step = 91
#b = [a[i:i+step] for i in range(0,len(a),step)]
#print(b)


In [3]:
data1 = data.iloc[:,1:]
scaler = MinMaxScaler(feature_range=(0,1))
data2 = scaler.fit_transform(data1)
print('归一化结果为：\n{}'.format(data2))

归一化结果为：
[[0.         0.00869521 0.00806596 ... 0.06899994 0.06635265 0.0108034 ]
 [0.00875436 0.         0.00476927 ... 0.06241226 0.05972588 0.01153127]
 [0.00811177 0.00476395 0.         ... 0.06133179 0.05863317 0.01096641]
 ...
 [0.07271909 0.06533189 0.06427255 ... 0.         0.00452545 0.07061145]
 [0.06964298 0.06226403 0.06119313 ... 0.00450694 0.         0.06701812]
 [0.01076655 0.01141429 0.01086727 ... 0.06677155 0.063634   0.        ]]


In [4]:
#存储文件
Save_filename = r'dis_归一化.csv'
Save_path =  r'C:\Users\zzsgdsg7\Desktop'
data3 = pd.DataFrame(data2)
data3.to_csv(Save_path + "\\" + Save_filename, encoding="utf_8_sig")  # 保存成.csv文件
